### ISSUE TITLE
About STL

### ISSUE THREAD

**Issue by adelarsq** [benjones/rustVsCpp#1]
Would be nice also to compare with STL. 😄

**Comment by benjones** [comment]
Which parts?  This seems to do a reasonable job for a lot of the
containers:
https://docs.google.com/presentation/d/1q-c7UAyrUlM-eZyTo1pd8SZ0qwA_wYxmPZVOQkoDmH4/edit?usp=sharing

**Comment by adelarsq** [comment]
Thanks for share. I will close the issue 😃
